УСТАНОВКА PSYCOPG2

In [582]:
# !pip install psycopg2

Начинаем с импорта библиотек

In [583]:
import pandas as pd
import psycopg2

базы параметры

In [584]:
# DBNAME = 'skillfactory'
DBNAME = 'project_sql'
USER = 'skillfactory'
PASSWORD = 'cCkxxLVrDE8EbvjueeMedPKt'
HOST = '84.201.134.129'
PORT = 5432

Создаем соединение с заданными параметрами

In [610]:
connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)

Запрос

In [586]:
def zapr(query ) -> df:
    """Функция запроса к базе SQL

    Args:
        query (_str_): запрос принимаем ввиде строки

    Returns:
        df: Возвращаем полученый DataFrame
    """
    global connection 
    # используем метод read_sql_query, чтобы получить результаты запроса сразу в виде датафрейма
    df = pd.read_sql_query(query, connection)#, index_col='id')
    return df

### 3.1
Сколько вакансий есть в базе

In [621]:
# код запроса представляет из себя строковую переменную
n = 10
query = f'''select COUNT(id)
            from vacancies
         '''
df = zapr(query)
print('Количество вакансий:', zapr(query )['count'].iloc[0])

Количество вакансий: 49197

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

### 3.2
Сколько работодателей

In [623]:
query = f'''select COUNT(id)
            from employers            
        '''
print('Количество работодателей:', zapr(query )['count'].iloc[0])

Количество работодателей: 23501

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

### 3.3
Сколько регионов

In [624]:
query = f'''select COUNT(id)
            from areas            
        '''
print('Количество регионов:', zapr(query )['count'].iloc[0])

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

Количество регионов: 1362

### 3.4
Сколько сфер деятельности

In [625]:
query = f'''select COUNT(id)
            from industries  
        '''
print('Количество сфер деятельности:', zapr(query )['count'].iloc[0])

Количество сфер деятельности: 294

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

### 4.1
запрос, который позволит узнать, сколько (cnt) вакансий в каждом регионе (area)

In [590]:
n = 5
query = f'''select a.name
            from VACANCIES AS v
               LEFT JOIN AREAS AS a ON v.area_id=a.id
            GROUP BY a.name
            ORDER BY COUNT(*) DESC
            LIMIT {n}
         '''
zapr(query)

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

              name
0           Москва
1  Санкт-Петербург
2            Минск
3      Новосибирск
4           Алматы

### 4.2
количества вакансий заполнено хотя бы одно из двух полей с зарплатой

In [626]:
query = f'''select COUNT(*)
            from VACANCIES
            WHERE salary_from is NOT NULL OR salary_to is NOT NULL
               
         '''
print('количества вакансий:', zapr(query)['count'].iloc[0])

количества вакансий: 24073

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

### 4.3
средние значения для нижней и верхней границы зарплатной вилки. Округлите значения до целого числа

In [592]:
query = f'''select ROUND(AVG(salary_from)) AS AVG_MIN,
                    ROUND(AVG(salary_to)) AS AVG_MAX
            from VACANCIES     
         '''
print ('значения нижней и верхней границы зарплаты')
zapr(query).iloc[0]

значения нижней и верхней границы зарплаты

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

avg_min     71065.0
avg_max    110537.0
Name: 0, dtype: float64

### 4.4
запрос, который выведет количество вакансий для каждого сочетания типа рабочего графика (schedule) и типа трудоустройства (employment), используемого в вакансиях. Какая пара находится на втором месте по популярности

In [593]:
query = f'''select schedule,
                    employment
            from VACANCIES 
            GROUP BY  schedule, employment 
            ORDER BY COUNT(*) DESC
            OFFSET 1
            LIMIT 1 
         '''
zapr(query)

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

           schedule        employment
0  Удаленная работа  Полная занятость

### 4.5
запрос, выводящий значения поля Требуемый опыт работы (experience) в порядке возрастания количества вакансий, в которых указан данный вариант опыта

In [594]:
n=10
query = f'''select experience
            from VACANCIES 
            GROUP BY experience
            ORDER BY COUNT(*)
         '''
zapr(query)

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

           experience
0         Более 6 лет
1           Нет опыта
2       От 3 до 6 лет
3  От 1 года до 3 лет

### 5.1
запрос, который позволит узнать, какие работодатели находятся на первом и пятом месте по количеству вакансий

In [650]:
query = f'''SELECT name
            FROM
                (select e.name,
                    ROW_NUMBER() OVER(ORDER BY COUNT(*) DESC) AS rnk
                from VACANCIES AS v
                     LEFT JOIN EMPLOYERS AS e ON v.employer_id=e.id
                GROUP BY e.name) AS d
            WHERE rnk=1 OR rnk=5
            ORDER BY rnk
            
         '''
zapr(query)

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

            name
0         Яндекс
1  Газпром нефть

### 5.2
запрос, который для каждого региона выведет количество работодателей и вакансий в нём.

Среди регионов, в которых нет вакансий, найдите тот, в котором наибольшее количество работодателей. Впишите его название в поле ниже в том виде, который вернул запрос

In [596]:
query = f'''WITH a AS
            (select a.name AS name_v,
                COUNT(v.id) AS count_v
            from AREAS AS a
                LEFT JOIN VACANCIES AS v ON v.area_id=a.id   
            GROUP BY a.name),
            
            b AS
            (SELECT a.name AS name_e,
                COUNT(e.id) AS count_e
            FROM AREAS AS a
                LEFT JOIN EMPLOYERS AS e ON a.id=e.area
            GROUP BY a.name)
            
            SELECT name_v AS name
            FROM a JOIN b ON a.name_v=b.name_e
            WHERE count_v=0
            ORDER BY count_e DESC
            LIMIT 1
         '''
         
zapr(query)

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

     name
0  Россия

### 5.3
Для каждого работодателя посчитайте количество регионов, в которых он публикует свои вакансии.

Выберите максимальное значение из получившегося списка

In [597]:
query = f'''WITH a AS
            (SELECT e.name AS name_e,
                    a.name AS name_a,
                    count(*) AS cnt
            from VACANCIES AS v
                LEFT JOIN AREAS AS a  ON v.area_id=a.id
                LEFT JOIN EMPLOYERS AS e ON  v.employer_id=e.id
            GROUP BY e.name, a.name
            )
                        
            SELECT name_e,
                    count(*)
            FROM a
            GROUP BY name_e 
            ORDER BY COUNT(*) DESC
         '''
zapr(query)

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

                                                  name_e  count
0                                                 Яндекс    181
1                                             Ростелеком    152
2                                             Спецремонт    116
3                                 Поляков Денис Иванович     88
4                                              ООО ЕФИН      71
...                                                  ...    ...
14761                                      Русская дымка      1
14762                                         Интеркросс      1
14763  Автономная некоммерческая организация Московск...      1
14764                 Транспортный холдинг города Алматы      1
14765                                        СептикГрупп      1

[14766 rows x 2 columns]

### 5.4
запрос для подсчёта количества работодателей, у которых не указана сфера деятельности

In [627]:
query = f'''SELECT COUNT(*)
            from EMPLOYERS AS e
                LEFT JOIN EMPLOYERS_INDUSTRIES AS ei  ON e.id=ei.employer_id
            WHERE industry_id is NULL
        '''
print ('количества работодателей, у которых не указана сфера деятельности:',zapr(query)['count'].iloc[0])

количества работодателей, у которых не указана сфера деятельности: 8419

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

### 5.5
запрос, чтобы узнать название компании, находящейся на третьем месте в алфавитном списке (по названию) компаний, у которых указано четыре сферы деятельности

In [637]:
query = f'''SELECT e.name
            from EMPLOYERS AS e
                LEFT JOIN EMPLOYERS_INDUSTRIES AS ei  ON e.id=ei.employer_id
                LEFT JOIN INDUSTRIES AS i ON i.id=ei.industry_id
            WHERE i.name is NOT NULL
            GROUP BY e.name
            HAVING COUNT(DISTINCT i.name)=4
            ORDER BY e.name
            OFFSET 2 LIMIT 1
        '''
print('название компании, находящейся на третьем месте в алфавитном списке:', zapr(query).iloc[0,0])

название компании, находящейся на третьем месте в алфавитном списке: 2ГИС

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

### 5.6
запроса выясните, у какого количества работодателей в качестве сферы деятельности указана «Разработка программного обеспечения»

In [629]:
query = f'''SELECT COUNT(e.id)                   
            from EMPLOYERS AS e
                LEFT JOIN EMPLOYERS_INDUSTRIES AS ei  ON e.id=ei.employer_id
                LEFT JOIN INDUSTRIES AS i ON i.id=ei.industry_id
            WHERE i.name='Разработка программного обеспечения'
        '''
print('количества работодателей в качестве сферы деятельности указана «Разработка программного обеспечения»', zapr(query)['count'].iloc[0])

количества работодателей в качестве сферы деятельности указана «Разработка программного обеспечения» 3553

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

### 5.7
Для компании «Яндекс» выведите список регионов-миллионников , в которых представлены вакансии компании, вместе с количеством вакансий в этих регионах. Также добавьте строку Total с общим количеством вакансий компании, собранных в этой таблице

In [601]:
million_cities = ['Москва', 'Санкт-Петербург','Новосибирск', 'Екатеринбург','Нижний Новгород','Казань', 'Челябинск',
                  'Омск', 'Самара', 'Ростов-на-Дону', 'Краснодар', 'Уфа', 'Красноярск', 'Пермь', 'Воронеж','Волгоград']
list_str="'"+"','".join(million_cities)+"'"
query = f'''WITH yande AS
            (SELECT a.name,
                    COUNT(*) AS cnt                   
            from VACANCIES AS v
                LEFT JOIN AREAS AS a  ON v.area_id=a.id
                LEFT JOIN EMPLOYERS AS e  ON v.employer_id=e.id
            WHERE e.name='Яндекс' AND a.name in ({list_str})
            GROUP BY a.name)
            
            (SELECT *
            FROM yande
            ORDER BY 2,1)
            UNION ALL
            SELECT 'Total',SUM(cnt)
            FROM yande
        '''
zapr(query)

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

               name    cnt
0              Омск   21.0
1         Челябинск   22.0
2        Красноярск   23.0
3         Волгоград   24.0
4            Казань   25.0
5             Пермь   25.0
6    Ростов-на-Дону   25.0
7            Самара   26.0
8               Уфа   26.0
9         Краснодар   30.0
10          Воронеж   32.0
11      Новосибирск   35.0
12  Нижний Новгород   36.0
13     Екатеринбург   39.0
14  Санкт-Петербург   42.0
15           Москва   54.0
16            Total  485.0

### 6.1
Сколько вакансий имеет отношение к данным

In [630]:
query = f'''SELECT COUNT(id)                
            from VACANCIES
            WHERE name iLIKE '%data%' or name iLIKE '%данн%'            
        '''
print('вакансий имеет отношение к данным:',zapr(query)['count'].iloc[0])

вакансий имеет отношение к данным: 1771

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

### 6.2
Сколько есть подходящих вакансий для начинающего дата-сайентиста?

Будем считать вакансиями для дата-сайентистов такие, в названии которых есть хотя бы одно из следующих сочетаний

# ВЕРСИЯ 2,0

In [636]:
pro_list =["data scientist","data science","исследователь данных","machine learning"]
str_list="name iLIKE '%машинн%обучен%' OR ( name LIKE '%ML%' AND name NOT LIKE '%HTML%' )"
for index in pro_list:
    str_list+=f" OR name iLIKE '%{index}%'"
  
str_jun="( experience='Нет опыта' OR employment='Стажировка' OR name iLIKE '%junior%' )"

query = f'''SELECT COUNT(id)                  
            from VACANCIES
            WHERE ({str_list} ) AND {str_jun}
        '''
print('подходящих вакансий для начинающего дата-сайентиста:',zapr(query)['count'].iloc[0])

подходящих вакансий для начинающего дата-сайентиста: 51

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

# ВЕРСИЯ 3,0

In [604]:
str_list="name iLIKE any('{%data scientist%, %data science%, %исследователь данных%, %machine learning%, %машинн%обучен%}') OR ( name LIKE '%ML%' AND name NOT LIKE '%HTML%' )"
  
str_jun="( experience='Нет опыта' OR employment='Стажировка' OR name iLIKE '%junior%' )"

query = f'''SELECT COUNT(id)                  
            FROM public.vacancies
            WHERE ({str_list}) AND {str_jun}
        '''

### 6.3
Сколько есть вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres

In [632]:
pro_list =["data scientist","data science","исследователь данных","machine learning"]
str_list="name iLIKE '%машинн%обучен%' OR ( name LIKE '%ML%' AND name NOT LIKE '%HTML%' )"
for index in pro_list:
    str_list+=f" OR name iLIKE '%{index}%'"
  
str_jun="( key_skills LIKE '%SQL%' OR key_skills LIKE '%postgres%' )"

query = f'''SELECT COUNT(id)                 
            FROM vacancies
            WHERE ({str_list}) AND {str_jun}
        '''
print('вакансий для дата-сайентиста со знанием SQL:',zapr(query)['count'].iloc[0])

вакансий для дата-сайентиста со знанием SQL: 201

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

### 6.4

С помощью запроса, аналогичного предыдущему, проверьте, насколько популярен Python в требованиях работодателей к DS. Вычислите количество вакансий, в которых в качестве ключевого навыка указан Python.

In [634]:
pro_list =["data scientist","data science","исследователь данных","machine learning"]
str_list="name iLIKE '%машинн%обучен%' OR ( name LIKE '%ML%' AND name NOT LIKE '%HTML%' )"
for index in pro_list:
    str_list+=f" OR name iLIKE '%{index}%'"
  
str_jun="( key_skills ilike '%Python%' )"

query = f'''SELECT COUNT(name)                 
            FROM vacancies
            WHERE ({str_list}) AND {str_jun}
        '''
        
print('вакансий для дата-сайентиста со знанием Python:',zapr(query)['count'].iloc[0])

вакансий для дата-сайентиста со знанием Python: 351

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

### 6.5
Сколько ключевых навыков в среднем указывают в вакансиях для DS

In [635]:
pro_list =["data scientist","data science","исследователь данных","machine learning"]
str_list="name iLIKE '%машинн%обучен%' OR ( name LIKE '%ML%' AND name NOT LIKE '%HTML%' )"
for index in pro_list:
    str_list+=f" OR name iLIKE '%{index}%'"


query = f'''SELECT ROUND(AVG(length(key_skills) - length(replace(key_skills,'\t','')) +1),2)             
            FROM vacancies
            WHERE ({str_list}) AND key_skills IS NOT NULL
        '''
print('Сколько ключевых навыков:',zapr(query).iloc[0,0])

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

Сколько ключевых навыков: 6.41

### 6.6
Напишите запрос, позволяющий вычислить, какую зарплату для DS в среднем указывают для каждого типа требуемого опыта (уникальное значение из поля experience)

In [608]:
pro_list =["data scientist","data science","исследователь данных","machine learning"]
str_list="name iLIKE '%машинн%обучен%' OR ( name LIKE '%ML%' AND name NOT LIKE '%HTML%' )"
for index in pro_list:
    str_list+=f" OR name iLIKE '%{index}%'"


query = f'''SELECT experience, ROUND(AVG((COALESCE(salary_from , salary_to)+COALESCE(salary_to , salary_from))/2))            
            FROM vacancies
            WHERE ({str_list}) AND (salary_from IS NOT NULL OR salary_to IS NOT NULL)
            GROUP BY experience
        '''
zapr(query)

C:\Users\Temnykov\AppData\Local\Temp\ipykernel_6816\218144759.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, connection)#, index_col='id')

           experience     round
0           Нет опыта   74643.0
1  От 1 года до 3 лет  139675.0
2       От 3 до 6 лет  243115.0

In [651]:
# не забываем закрыть соединение после окончания работы
connection.close()